### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by Tripwyr** [hikarin-dev/Auto-Crafter#3]
I'm getting this error when loading the game, and it also shows up each time I manually craft anything. I do not see the overlay in-game and the trigger config looks like this: 
![image](https://github.com/gynryiie/Auto-Crafter/assets/16571812/289e7b87-880e-449d-bc20-e52016a8899a)

This is the error: 2023-05-25 14:24:32.598	Error	Exception: The given key was not present in the dictionary.

Please let me know if there are any logs I can pull to assist

**Comment by hikarin-dev** [comment]
The error shouldn't cause any problem with the macro's functionality, it has something to do with mutex, and I honestly couldn't get the error to go away without breaking the macro. :(

As for the overlay not showing, it could be that the crafting is still turned off, try typing `/e ac` in game to toggle it on

**Comment by Tripwyr** [comment]
That is an embarassing mistake, I had been trying to /e ac on. Works fine
