### ISSUE TITLE
error turning on autocrafter 

### ISSUE THREAD

**Issue by ghost** [hikarin-dev/Auto-Crafter#7]
when i turn on autocrafter i get an error notification its been working fine i use it a lot nothing changed here is the error box
![Screenshot 2024-05-13 145634](https://github.com/gynryiie/Auto-Crafter/assets/46291278/ef8ba721-e1d9-4ba1-8924-a96068ecebd8)

the display doesnt show on the top right either

**Comment by hikarin-dev** [comment]
latest Triggernometry update broke an unconventional expression i wrote. 
Try to update your trigger to v.2.4.0 and see if that solves the issue.

**Comment by middleeast856** [comment]
yes it fixed it thanks

**Comment by middleeast856** [comment]
/e autocraft 2 shuts off autocrafter
![Screenshot 2024-05-16 021340](https://github.com/gynryiie/Auto-Crafter/assets/46291278/7039480e-2ef7-45d0-9ad9-7faac5b02a6f)

**Comment by ghost** [comment]
when i turn autocrafter on i get this
![Screenshot 2024-05-16 021738](https://github.com/gynryiie/Auto-Crafter/assets/46291278/916fc6e0-f3be-47ee-8636-d725326273e0)
the info bar shows up now but when i do /e autocraft 2 autocrafter turns off and i get this
![Screenshot 2024-05-16 021340](https://github.com/gynryiie/Auto-Crafter/assets/46291278/ef5dfd7d-b036-4605-9306-e31660384867)

**Comment by Maou-Sadao** [comment]
@middleeast856 Did you happen to find a solution for this? I'm getting the exact same error with the latest versions of triggernometry
